mailgun:
  from: 'James Lafa <james+wundermarks@jlafa.com>'
  admin_email: 'James Lafa <james+wundermarks@jlafa.com>'

facebook:
  app_id: '1746824045575538'

bookmarklet:
  current_version: '1469795199'
